### ISSUE TITLE
Paste organization number in IE11 does not validate correctly

### ISSUE THREAD

**Issue by johanssonpeter** [FlaxHaxx/angular-input-types#2]
Reproduction:

Open https://www.blitter.se/angular-input-types/examples/ in IE11.

Paste in organization number 2120000142.

Expected: OK validation.

Got: Failed validation.

I noticed line 46 in orgnr.js differs in IE11 vs Chrome 
`return ctrl.$isEmpty(modelValue) || validate.orgnr(viewValue); `

In Chrome, the `modelValue` and `viewValue` is formatted but in IE11 there is no formatting.

**Comment by FlaxHaxx** [comment]
I have verified the bug and will fix it as soon as I can.

**Comment by FlaxHaxx** [comment]
Fixed in version [2.0.2](https://github.com/FlaxHaxx/angular-input-types/releases/tag/2.0.2)
